version: "3.9"
services:
  sliderule:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/sliderule:unstable
    container_name: sliderule
    network_mode: "host"
    restart: unless-stopped
    pull_policy: if_not_present
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - /plugins:/plugins
    environment:
      - LOG_FORMAT="FMT_TEXT"
      - IPV4=127.0.0.1
      - ENVIRONMENT_VERSION=unknown
      - ORCHESTRATOR=http://127.0.0.1:8050
      - CLUSTER=local
      - AMS=http://127.0.0.1:9082
      - IS_PUBLIC=false
      - CONTAINER_REGISTRY=742127912612.dkr.ecr.us-west-2.amazonaws.com
    labels:
      - autoheal=true
    healthcheck:
      test: curl -f -X GET -d "{}" http://localhost:9081/source/health
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 30s
  ilb:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/ilb:unstable
    container_name: ilb
    network_mode: "host"
    restart: unless-stopped
    pull_policy: if_not_present
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./:/haproxy
      - /etc/ssl/private:/etc/ssl/private
      - /etc/haproxy/pem/:/etc/haproxy/pem/
    environment:
      - IS_PUBLIC=true
      - JWT_ISSUER=https://login.slideruleearth.io
      - CLUSTER=local
    labels:
      - autoheal=true
    healthcheck:
      test: curl -f http://localhost:8050/discovery/health
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 30s
  monitor:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/monitor:unstable
    container_name: monitor
    network_mode: host
    restart: unless-stopped
    pull_policy: if_not_present
  monitor-agent:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/monitor-agent:unstable
    container_name: monitor-agent
    network_mode: host
    restart: unless-stopped
    pull_policy: if_not_present
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
  proxy:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/proxy:unstable
    container_name: proxy
    network_mode: "host"
    restart: unless-stopped
    pull_policy: if_not_present
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /usr/local/etc/docker-entrypoint.sh
    volumes:
      - /etc/ssl/private:/etc/ssl/private
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DOMAIN=$DOMAIN
      - REDIRECT_URI_SCHEME=http
  ams:
    image: 742127912612.dkr.ecr.us-west-2.amazonaws.com/ams:unstable
    container_name: ams
    network_mode: "host"
    restart: always
    pull_policy: if_not_present
    entrypoint: /docker-entrypoint.sh
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /data:/data
