version: "3.9"
services:
  monitor-agent:
    image: ${MONITOR_AGENT_IMAGE}
    container_name: monitor-agent
    network_mode: host
    pid: host
    restart: unless-stopped
    pull_policy: if_not_present
    entrypoint: /usr/local/etc/docker-entrypoint.sh
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      # node exporter
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      # promtail
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    labels:
      - autoheal=true
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
