version: "3.9"
services:
  ilb:
    image: ${ILB_IMAGE}
    network_mode: "host"
    restart: always
    pull_policy: if_not_present
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /haproxy:/haproxy
      - /etc/ssl/private:/etc/ssl/private
    environment:
      - IS_PUBLIC=$IS_PUBLIC
      - ORGANIZATION=$ORGANIZATION
      - DOMAIN=$DOMAIN
      - OAUTH_HMAC_SECRET=$OAUTH_HMAC_SECRET
    healthcheck:
      test: curl -f http://localhost:8050/discovery/health
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 30s
    labels:
      - autoheal=true
  monitor-agent:
    image:  ${MONITOR_AGENT_IMAGE}
    network_mode: host
    restart: unless-stopped
    pull_policy: if_not_present
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    labels:
      - autoheal=true
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
