repos:
        # Fix common spelling mistakes
        - repo: https://github.com/codespell-project/codespell
          rev: v2.2.6
          hooks:
                - id: codespell
                  args: [
                    '--ignore-words-list', 'parm,parms',
                    '--'
                  ]
                  types_or: [python, rst, markdown]
                  files: ^(applications|clients|datasets|docs|packages|platforms|targets)/