# conda env create -f environment.yml
name: sliderule
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - geopandas
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyproj
  - pytables
  - pytest
  - python<3.14   # cap Python because fiona and geospatial stack is not fully 3.14+ ready
  - python-pdal>=3.0.0
  - requests
  - scikit-learn
  - scipy
  - setuptools_scm
  - shapely
  - sliderule
  - tk
  - xyzservices
