# conda env create -f environment.yml
name: sliderule_notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - duckdb
  - geojson
  - geopandas
  - h5coro
  - h5py
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyproj
  - pytest
  - python
  - python-pdal>=3.0.0
  - pytables
  - requests
  - scikit-learn
  - scipy
  - setuptools_scm
  - shapely
  - sliderule
  - tk
  - xyzservices