global:

  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:

    # System Metrics for Cluster
  - job_name: 'sliderule_sys'
    ec2_sd_configs:
      - region: us-west-2
        port: 9100
    relabel_configs:
        # Only monitor instances with a Name ending with "-node"
      - source_labels: [__meta_ec2_tag_Name]
        regex: .*-node
        action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance

    # Application Metrics for Cluster
  - job_name: 'sliderule_app'
    ec2_sd_configs:
      - region: us-west-2
        port: 9081
    metrics_path: "/probe/prometheus"
    relabel_configs:
        # Only monitor instances with a Name ending with "-node"
      - source_labels: [__meta_ec2_tag_Name]
        regex: .*-node
        action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance

    # System Metrics for Monitor
  - job_name: 'monitor_sys'
    static_configs:
      - targets: ['localhost:9100']

    # System Metrics for Orchestrator
  - job_name: 'orchestrator_sys'
    static_configs:
      - targets: ['10.0.1.5:9100']

    # Application Metrics for Orchestrator
  - job_name: 'orchestrator_app'
    static_configs:
      - targets: ['10.0.1.5:8050']
    metrics_path: "/discovery/prometheus"
