name: Asset Metadata Service (AMS) Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 5' # Every Sunday at 10 pm

jobs:
  test:
    name: ams-test
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::742127912612:role/GitHubAction-S3ReadAssets
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Download ATL13 config files from S3
        shell: bash -l {0}
        run: |
          sudo mkdir -p /data/ATL13
          sudo chmod -R 777 /data/ATL13
          aws s3 cp s3://sliderule/config/atl13.json /data/ATL13/atl13.json --no-progress
          aws s3 cp s3://sliderule/config/atl13.db /data/ATL13/atl13.db  --no-progress
          aws s3 cp s3://sliderule/config/3dep.db /data/3DEP/3dep.db  --no-progress

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: ams
          environment-file: applications/ams/environment.yml

      - name: Run AMS tests with coverage
        shell: bash -l {0}
        working-directory: applications/ams
        run: |
          make test
